micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:h2:mem:cdcdb`}
    driverClassName: org.h2.Driver
    username: ${DB_USER:cdc}
    password: ${DB_PASSWORD:cdc}
    schema-generate: CREATE_DROP
    dialect: H2