micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: devjs
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jpa.default.properties.hibernate.hbm2ddl.auto: update

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#    dialect: H2
#    jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true